name: Build and Deploy Quartz

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository with Quartz configuration
    - name: Checkout Quartz repository
      uses: actions/checkout@v3
    # 2. Clone the Markdown content repository
    - name: Clone Markdown content repository
      run: |
        git clone https://github.com/Screedy/UPOL-SZZ-Otazky.git content
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Build
      uses: konstfish/quartz-build-action@v1
      with:
        source: content
        page_title: "Statnice"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
